### Test signup
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "email": "sdfjkghsjkadfjshkj@g.com",
    "password": "123"
}

### Test login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "a@g.com", 
    "password": "123"
}

### Test dashboard
GET http://localhost:3000/api/user/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTcyMjUxNDcyOSwiZXhwIjoxNzIyNTE1NjI5fQ.hFAItSVCde96ZsDDrzO3R84qMv76Um5nP_m8kXvaXNE

